name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run pytest -v
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          REG_MAIL_API_KEY: ${{ secrets.REG_MAIL_API_KEY }}
          TEMP_MAIL_API_KEY: ${{ secrets.TEMP_MAIL_API_KEY }}
          ANTICAPTCHA_KEY: ${{ secrets.ANTICAPTCHA_KEY }}
